template_path: eb_bridgepf.yaml
stack_name: bridgepf-prod
parameters:
  AwsSnsBounceNotificationEndpoint: bridge-bounce-notifications@sagebase.org
  DNSHostname: bridgepf-prod
  Server2EndpointUrl: bridgeserver2-prod.sagebridge.org
