template_path: eb_bridgepf.yaml
stack_name: bridgepf-develop
parameters:
  AwsSnsBounceNotificationEndpoint: bridgepf-develop-bounce-notifications@sagebase.org
  DNSHostname: bridgepf-develop
  Server2EndpointUrl: bridgeserver2-develop.sagebridge.org
