template_path: eb_bridgepf.yaml
stack_name: bridgepf-uat
parameters:
  AwsSnsBounceNotificationEndpoint: bridgepf-uat-bounce-notifications@sagebase.org
  DNSHostname: bridgepf-uat
  Server2EndpointUrl: bridgeserver2-uat.sagebridge.org
