Description: Resources for BridgePF Application
AWSTemplateFormatVersion: 2010-09-09
Outputs:
  AWSS3UserSignedConsentsDownloadBucket:
    Value: !Ref AWSS3UserSignedConsentsDownloadBucket
    Export:
      Name: !Sub '${AWS::StackName}-UserSignedConsentsDownloadBucket'
  LoadBalancerAccessLogsBucket:
    Value: !Ref LoadBalancerAccessLogsBucket
    Export:
      Name: !Sub '${AWS::StackName}-LoadBalancerAccessLogsBucket'
Parameters:
  AwsSnsBounceNotificationEndpoint:
    Type: String
    Description: Email address for SNS bounce notifications
  DNSHostname:
    Type: String
    Description: DNS Hostname for deployment
  Server2EndpointUrl:
    Type: String
    Description: Server2 endpoint URL, so we can forward Route 53 records to Server2. For Example, bridgeserver2-prod.sagebridge.org
Resources:
  LoadBalancerAccessLogsBucket:
    Type: 'AWS::S3::Bucket'
  LoadBalancerAccessLogsBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref LoadBalancerAccessLogsBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: ModAccess
            Action:
              - 's3:PutObject'
            Effect: Allow
            Resource:
              - !Join
                - ''
                - - !GetAtt LoadBalancerAccessLogsBucket.Arn
                  - '/*'
            Principal:
              AWS:
                - 127311923021
  AWSR53RecordSet:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneName: 'sagebridge.org.'
      Name: !Join
        - ''
        - - !Ref DNSHostname
          - '.sagebridge.org.'
      Type: CNAME
      TTL: '900'
      ResourceRecords:
        - !Ref Server2EndpointUrl
  AWSSNSBounceTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      Subscription:
        -
          Endpoint: !Ref AwsSnsBounceNotificationEndpoint
          Protocol: "email"
  # Buckets for signed consents that users can download
  AWSS3UserSignedConsentsDownloadBucket:
    Type: 'AWS::S3::Bucket'
